_BASE_: Base-attribute.yml

DATASETS:
  NAMES: ("CarAttr",)
  TESTS: ("CarAttr",)

MODEL:
  BACKBONE:
    NAME: build_resnet_backbone
    DEPTH: 18x
    NORM: BN
    LAST_STRIDE: 2
    FEAT_DIM: 512
    PRETRAIN: False

  HEADS:
    NUM_TYPES: 2
    NUM_TYPE_CLASSES: [23,8]

INPUT:
  SIZE_TRAIN: [ 128, 256 ]
  SIZE_TEST: [ 128, 256 ]

  FLIP:
    ENABLED: False

  PADDING:
    ENABLED: False

DATALOADER:
  NUM_INSTANCE: 2
  NUM_WORKERS: 6

SOLVER:
  IMS_PER_BATCH: 2

TEST:
  EVAL_PERIOD: 1
  IMS_PER_BATCH: 2

OUTPUT_DIR: projects/FastAttr/logs/pa100k/strong_baseline